Matplotlib:
  abstract: 本文介绍了 Python 最广为使用的科学绘图库 Matplotlib
  category: Python
  keywords:
  - python
  - matplotlib
  - plot
  - computing
  last_modified: '2020-08-11'
  series: Python-libs
_homepage:
  online_date: 2020-08-10
  previous_online_date: 2017-01-07
